version: "3.9"
services:
  go-fs:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "./config/config-docker.yaml:/cdn/config.yaml:ro"
    # environment: # Override Example
    #   - "APP_TELEMETRY_JAEGER_ADDRESS="
    #   - "APP_TELEMETRY_JAEGER_PORT="
    depends_on:
      - "consul"
      - "redis"
      - "postgres"
      - "jaeger"

  redis:
    image: "redis:7-alpine"
    volumes:
      - "./config/redis.conf:/redis.conf"
    command: "redis-server /redis.conf"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: go_fs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  haproxy:
    image: haproxy:latest
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "1936:1936" # haproxy stats

  consul:
    extends:
      file: ./docker-compose-consul-dev.yml
      service: consul

  jaeger:
    extends:
      file: ./docker-compose-jaeger-dev.yml
      service: jaeger

volumes:
  pgdata:
