version: "3.9"
services:
  consul:
    image: hashicorp/consul:latest
    volumes:
     - ./config/consul.json:/consul/config/server.json
     - ./config/postgres.json:/consul/config/postgres.json
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"
