version: "3.9"
services:
  consul:
    image: hashicorp/consul:latest
    volumes:
     - ./config/consul.json:/consul/config/server.json
     - ./config/postgres.json.sample:/consul/config/postgres.json
     - ./config/redis.json.sample:/consul/config/redis.json
     - ./config/jaeger.json.sample:/consul/config/jaeger.json
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"
