version: "3.9"
services:
  redis:
    extends:
      file: ./docker-compose.yml
      service: redis
    ports:
      - "6379:6379"

  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres

  haproxy:
    extends:
      file: ./docker-compose.yml
      service: haproxy

  consul:
    extends:
      file: ./docker-compose-consul-dev.yml
      service: consul

  jaeger:
    extends:
      file: ./docker-compose-jaeger-dev.yml
      service: jaeger

volumes:
  pgdata:
