version: "3.9"
services:
  redis:
    extends:
      file: ./docker-compose.yml
      service: redis

  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres

  haproxy:
    extends:
      file: ./docker-compose.yml
      service: haproxy

  consul:
    extends:
      file: ./docker-compose.yml
      service: consul

  jaeger:
    extends:
      file: ./docker-compose.yml
      service: jaeger

volumes:
  pgdata:
