apiVersion: v1
kind: Service
metadata:
  name: go-cdn-service
spec:
  type: LoadBalancer
  selector:
    app: go-cdn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
status:
  loadBalancer:
    ingress:
    - ip: PUBLIC_IP
