apiVersion: v1
kind: Service
metadata:
  name: primary
  namespace: caching
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: primary
